# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='total',
            name='user',
        ),
        migrations.AddField(
            model_name='logs',
            name='total_day',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
