# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='total_day',
        ),
    ]
