# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20170103_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='total_month',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='total_week',
            field=models.FloatField(null=True),
        ),
    ]
